---

# TODO: Update to version 1.0
# https://dbdemon.com/pf_and_fail2ban/

- name: "fail2ban: Stat /usr/local/etc/rc.d/fail2ban"
  ansible.builtin.stat:
    path: /usr/local/etc/rc.d/fail2ban
  register: pf_fail2ban_service

- name: "fail2ban: Fail if fail2ban is enabled and no service exists"
  ansible.builtin.fail:
    msg: '[ERR] fail2ban is enabled, but no service exists.'
  when:
    - pf_fail2ban_enable|bool
    - not pf_fail2ban_service.stat.exists

- name: "fail2ban: Configure /usr/local/etc/fail2ban/fail2ban.local"
  ansible.builtin.template:
    dest: /usr/local/etc/fail2ban/fail2ban.local
    src: "{{ pf_fail2ban_local_template }}"
    owner: root
    group: wheel
    mode: '0644'
    backup: "{{ pf_backup_conf }}"
  notify: reload fail2ban
  when: pf_fail2ban_enable|bool
  vars:
    ini: "{{ pf_fail2ban_local_conf }}"

- name: "fail2ban: Configure /usr/local/etc/fail2ban/jail.local"
  ansible.builtin.template:
    dest: /usr/local/etc/fail2ban/jail.local
    src: "{{ pf_fail2ban_jail_local_template }}"
    owner: root
    group: wheel
    mode: '0644'
    backup: "{{ pf_backup_conf }}"
  notify: reload fail2ban
  when: pf_fail2ban_enable|bool
  vars:
    ini: "{{ pf_fail2ban_jail_local_conf }}"

# EOF
...
